### PR TITLE
Restructures and refreshes the README

### PR DESCRIPTION
**Pull request by ulrikandersen**
This PR restructures and refreshes the README in order to bring it up to date with what Fabrikt offers as of September 2024.

The contents are more or less the same, but I have tried to cater more to the users and to put an emphasis on how to get started.

### CODE REVIEW

**Review by cjbooms — APPROVED** [review]
Reads well. Nice work. Feel free to merge when happy

**Comment by cjbooms** [comment]
Should we also mention the Gradle plugin from @acanda? 
https://github.com/acanda/fabrikt-gradle-plugin
```
plugins {
    id("ch.acanda.gradle.fabrikt") version "1.1.0"
}

fabrikt {
    generate("dog") {
        apiFile = file("src/main/openapi/dog.yaml")
        basePackage = "com.example.api"
    }
}
```

**Comment by ulrikandersen** [comment]
> Should we also mention the Gradle plugin from @acanda? https://github.com/acanda/fabrikt-gradle-plugin

Certainly. I've added that 👍

**Comment by acanda** [comment]
> > Should we also mention the Gradle plugin from @acanda? https://github.com/acanda/fabrikt-gradle-plugin
> 
> Certainly. I've added that 👍

Hey, thanks! Now that the plugin's API is stable, I was just about to ask you if you'd like to add my plugin to your readme, but you beat me to it.

**Pull request merged**
