### PR TITLE
Support Micronaut controllers

### PR DESCRIPTION
**Pull request by atollk**
Fixes https://github.com/cjbooms/fabrikt/issues/154

At the moment, this is yet a draft. I haven't done any tests (neither automated unit tests, nor manual tests in practice) so far and might need to hash out some details for code generation. However, I would appreciate some input already, whether this is a solution which you'd be okay with in general.

### CODE REVIEW

**Comment by cjbooms** [comment]
Hi @atollk and thanks for your contribution. Apologies for the delayed response, I was on vacation until yesterday.

I like this approach and would be happy to accept the contribution. One question, did you consider just defining a new target instead of adding a tertiary controller configuration option? 
`CodeGenerationType.MICRONAUT_CONTROLLERS`

**Comment by atollk** [comment]
Hey, no worries. I didn't consider that option because it would feel somewhat odd to me that "models" and "Spring controllers" (which you'll often generate together) have the same relation to each other as "Micronaut controllers" and "Spring controllers" (which you'd probably need both at once). But I don't see any hard problems with that design either. So if you want me to change that, I can do it no problem.

Otherwise, I'll probably try to add some additional tests to this change and come back to you when I consider it completely ready for review.

**Comment by cjbooms** [comment]
> Hey, no worries. I didn't consider that option because it would feel somewhat odd to me that "models" and "Spring controllers" (which you'll often generate together) have the same relation to each other as "Micronaut controllers" and "Spring controllers" (which you'd probably need both at once). But I don't see any hard problems with that design either. So if you want me to change that, I can do it no problem.
> 
> Otherwise, I'll probably try to add some additional tests to this change and come back to you when I consider it completely ready for review.

Sounds good. Happy to go with your original approach, it'll work well.

**Comment by cjbooms** [comment]
> Hey, no worries. I didn't consider that option because it would feel somewhat odd to me that "models" and "Spring controllers" (which you'll often generate together) have the same relation to each other as "Micronaut controllers" and "Spring controllers" (which you'd probably need both at once). But I don't see any hard problems with that design either. So if you want me to change that, I can do it no problem.
> 
> Otherwise, I'll probably try to add some additional tests to this change and come back to you when I consider it completely ready for review.

Sounds good. Happy to go with your original approach, it'll work well.

**Comment by cjbooms** [comment]
Moved to #164

**Pull request closed without merging**
