### PR TITLE
Add support for the UUID format of strings

### LINKED ISSUE #56: Support String format UUID
A string with format type UUID should generate a data class using UUID instead of String.
```
   properties:
        stock_location_id:
          description: >
            The ID of the Stock Location from which this reservation should be fulfilled.
          type: string
          format: uuid
```
Should result in:
`val stockLocationId: UUID`

### PR DESCRIPTION
**Pull request by cjbooms**
Closes #56

### CODE REVIEW

**Comment by cjbooms** [comment]
👍

**Comment by cjbooms** [comment]
👍

**Comment by averabaq** [comment]
👍

**Comment by cjbooms** [comment]
Ah thanks @averabaq . I never know if I should ping you or not! :)

**Comment by averabaq** [comment]
Wrong icon, sorry. The comment was just to point out that I love these changes 🙂 
I'm always watching the repo, and I'm currently trying to sell it 😉

**Pull request merged**
