### PR TITLE
Add e2e tests for Ktor server interfaces

### PR DESCRIPTION
**Pull request by ulrikandersen**
This PR introduces end-to-end tests for the generated Ktor server interfaces.

The added tests serve a dual purpose:
1. **Functionality Verification:** Ensure that the generated interfaces function correctly within a Ktor server environment.
2. **Usage Examples:** Serve as practical examples demonstrating how to utilize the generated interfaces in a Ktor server setup.

Additionally, this PR reorganizes all end-to-end tests into a common end-to-end tests Gradle project ready for more subproject to be added ✨.

### CODE REVIEW

**Comment by cjbooms** [comment]
LGTM - Nice addition.

**Comment by cjbooms** [comment]
I have invited you as a collaborator also, just in case you have any interest. No pressure :)

**Comment by ulrikandersen** [comment]
> I have invited you as a collaborator also, just in case you have any interest. No pressure :)

I see great potential in this library, so I’ll happily accept the invitation. Do we have a communication channel apart from the issues/PRs here in the repo for coordinating our efforts?

**Comment by cjbooms** [comment]
> > I have invited you as a collaborator also, just in case you have any interest. No pressure :)
> 
> I see great potential in this library, so I’ll happily accept the invitation. Do we have a communication channel apart from the issues/PRs here in the repo for coordinating our efforts?

Nothing official yet. We have used google chat very occasionally, but mostly just comments on Issues PRs. I created a GH Discussion section, perhaps we could try that out. But open to any channel if you want to chat about something

**Pull request merged**
