### PR TITLE
Uses the first 2xx content media found es primary response type #239

### LINKED ISSUE #239: Multiple Return Types Generator Response Type Incorrect
When generating the interaction layer for making REST calls that have multiple return options, it seems to pick the first one and run with it. 

For example.. in bunny microservice (see spec file at bottom of bug)

The generated return type is `#/components/schemas/Failure`, rather than the correct one that is based on a 2xx response code `#/components/schemas/BunnyCreated`

I'd recommend a simple update to fix this to mimic what the other generators do.. I.E. choose the 2xx one as the primary response type and set that as the return type. 

Assuming that anything other than 2xx will throw an exception with some data about the response body in it, the clients can handle parsing the response body into the other generated models. I.E. `#/components/schemas/Failure`, as long as the models are still generated even though they are not tied to auto-parsing in the API response.

```
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Bunnies Microservice",
    "version" : "1.58.1"
  },
  "security" : [ {
    "api-key" : [ ]
  } ],
  "paths" : {
    "/api/v1/bunnies" : {
      "post" : {
        "tags" : [ "bunnies-controller" ],
        "summary" : "Bunnies API - submit bunnies for fun to an api.",
        "operationId" : "createBunny",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/CreateBunnyRequest"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "423" : {
            "description" : "Locked",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Failure"
                }
              }
            }
          },
          "500" : {
            "description" : "Internal Server Error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Failure"
                }
              }
            }
          },
          "201" : {
            "description" : "Created",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/BunnyCreated"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Failure"
                }
              }
            }
          },
          "422" : {
            "description" : "Unprocessable Entity",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Failure"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "CreateKillerBunny" : {
        "required" : [ "type" ],
        "type" : "object",
        "allOf" : [ {
          "$ref" : "#/components/schemas/CreateBunny"
        }, {
          "type" : "object",
          "properties" : {
            "killPreference" : {
              "type" : "string"
            }
          }
        } ]
      },
      "CreatePetBunny" : {
        "required" : [ "type" ],
        "type" : "object",
        "allOf" : [ {
          "$ref" : "#/components/schemas/CreateBunny"
        }, {
          "type" : "object",
          "properties" : {
            "bunnyColor" : {
              "type" : "string",
            }
          }
        } ]
      },
      "CreateEasterBunny" : {
        "required" : [ "type" ],
        "type" : "object",
        "allOf" : [ {
          "$ref" : "#/components/schemas/CreateBunny"
        }, {
          "type" : "object",
          "properties" : {
            "easterBunnyColor" : {
              "type" : "string"
            }
          }
        } ]
      },
      "CreateBunny" : {
        "required" : [ "type" ],
        "type" : "object",
        "properties" : {
          "size" : {
            "type" : "integer",
            "format" : "int64"
          },
          "submittedAt" : {
            "type" : "string",
            "format" : "date-time"
          }
        },
        "description" : "Create bunny parent object. All fields are required for any type of bunny.",
        "discriminator" : {
          "propertyName" : "type",
          "mapping" : {
            "PET_BUNNY" : "#/components/schemas/CreatePetBunny",
            "EASTER_BUNNY" : "#/components/schemas/CreateEasterBunny",
            "KILLER_BUNNY" : "#/components/schemas/CreateKillerBunny"
          }
        }
      },
      "CreateBunnyRequest" : {
        "required" : [ "createBunny" ],
        "type" : "object",
        "properties" : {
          "createBunny" : {
            "oneOf" : [ {
              "$ref" : "#/components/schemas/CreateKillerBunny"
            }, {
              "$ref" : "#/components/schemas/CreatePetBunny"
            }, {
              "$ref" : "#/components/schemas/CreateEasterBunny"
            } ]
          },
          "additional field" : {
            "type" : "boolean"
          }
        }
      },
      "Source" : {
        "type" : "string",
        "enum" : [ "GOOGLE", "BING" ]
      },
      "Failure" : {
        "required" : [ "error", "errorCode", "bunnyErrorTraceId" ],
        "type" : "object",
        "properties" : {
          "bunnyErrorTraceId" : {
            "type" : "string",
            "format" : "uuid"
          },
          "errorCode" : {
            "type" : "string"
          },
          "error" : {
            "type" : "string"
          },
          "subType" : {
            "type" : "string"
          }
        }
      },
      "Bunny" : {
        "required" : [ "id", "status", "size", "submittedDate" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int64"
          },
          "status" : {
            "$ref" : "#/components/schemas/BunnyStatus"
          },
          "size" : {
            "type" : "integer",
            "format" : "int64"
          },
          "submittedDate" : {
            "type" : "string",
            "format" : "date-time"
          }
        },
        "description" : "Representation of a bunny's current state."
      },
      "BunnyCreated" : {
        "required" : [ "bunny" ],
        "type" : "object",
        "properties" : {
          "bunny" : {
            "$ref" : "#/components/schemas/Bunny"
          }
        }
      },
      "BunnyStatus" : {
        "type" : "string",
        "enum" : [ "HAPPY", "ANGRY", "THAT_BUNNY_IS_A_KILLER" ]
      },
      "BunnyType" : {
        "type" : "string",
        "enum" : [ "PET_BUNNY", "EASTER_BUNNY", "KILLER_BUNNY" ]
      }
    },
    "securitySchemes" : {
      "api-key" : {
        "type" : "apiKey",
        "name" : "api-key",
        "in" : "header"
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by averabaq**
Uses the first 2xx content media found es primary response type #239
  * Upgrade dependencies & linter

Closes #239

### CODE REVIEW

**Comment by cjbooms** [comment]
👍

**Comment by cjbooms** [comment]
LGTM. Nice one @averabaq and thanks for the reminder

**Review by cjbooms — APPROVED** [review]

**Comment by thejeff77** [comment]
Awesome! Can't wait to give this a run!

**Comment by thejeff77** [comment]
Cool I can give this a run once 11.0.0 is released here: https://repo1.maven.org/maven2/com/cjbooms/fabrikt/

**Pull request merged**
